## numpy套件

In [1]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#numpy套件ndarray型態，提供element-wise的操作
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


In [3]:
print(type(a_ndarray))
print(a_ndarray.ndim) #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [4]:
z=np.zeros(6)
print(z)  #六個元素都為0的1d ndarray
print(np.zeros((2,6)))  #12個元素都為0的2d ndarray
print(np.empty((2,6,2))) #24個元素都未初始化的值
print(np.arange(10)) # 10個元素為0-9的1d ndarray

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 8.01097889e-307]
  [1.42417629e-306 8.45593934e-307]
  [6.89805151e-307 1.33511562e-306]
  [1.11260416e-306 8.45559303e-307]
  [1.06811422e-306 1.05694828e-307]
  [2.22522596e-306 1.33511969e-306]]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [5]:

my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [6]:
#2維ndarray取值
my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #第二列資料
print(my_2d_array[:,1]) #第二欄資料
print(my_2d_array[1,1]) #第二列第二欄的資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [7]:

#假設有六個組別"Modern Web", "DevOps", "Cloud", 
#"Big Data", "Security", "自我挑戰組"
#其參加人數分別為56, 8, 19, 14, 6, 71人
groups=["Modern Web", "DevOps",  "Cloud","Big Data", "Security", "自我挑戰組"]
ironman = [56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


In [8]:
#用人數去篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


## Ndarray轉置

In [9]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [10]:

print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [11]:

#ndarray nan(空值)
nan_array=np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]
